version: '3'
services:
  nginx:
    build:
      context: docker/nginx
    container_name: ocib_nginx
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:ro
    ports:
      - ${NGINX_PORT}:80
    networks:
      - network

  php:
    build:
      context: docker/php
    container_name: ocib_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ~/.composer:/.composer
    networks:
      - network

networks:
  network:
    driver: bridge