services:
  factory.client:
    class: DemigrantSoft\ClockInBot\Infrastructure\Service\ClockIn\ClientFactory
    arguments:
      - '@factory.client.ocean'

  factory.client.ocean:
    class: DemigrantSoft\ClockInBot\Infrastructure\Service\ClockIn\Ocean\OceanClientFactory