services:
  _defaults:
    public: true

  # Command
  command.user.register:
    class: DemigrantSoft\ClockInBot\Application\Command\User\Register\UserRegisterCommandHandler
    arguments:
      - '@service.user.creator'

  command.user.setup:
    class: DemigrantSoft\ClockInBot\Application\Command\User\SetUp\UserSetUpCommandHandler
    arguments:
      - '@repository.dbal.connection'
      - '@service.user.finder-by-reference'
      - '@service.user-settings.remover-by-user'
      - '@service.user-settings.creator'
      - '@service.user-data.creator'

  command.user.manual-clockin:
    class: DemigrantSoft\ClockInBot\Application\Command\User\ManualClockIn\UserManualClockInCommandHandler
    arguments:
      - '@service.user.finder-by-reference'
      - '@service.user-settings.finder-by-user'
      - '@service.user-settings.creator'
      - '@factory.client'

  # Query
  query.user.get-config:
    class: DemigrantSoft\ClockInBot\Application\Query\User\GetConfig\GetConfigQueryHandler
    arguments:
      - '@service.user.finder-by-reference'
      - '@service.user-settings.finder-by-user'
      - '@service.user-data.finder-by-user'
      - '@service.user-schedule.finder-by-user'
      - '@factory.client'

  query.user.get-clockins:
    class: DemigrantSoft\ClockInBot\Application\Query\User\GetClockIns\GetClockInsQueryHandler
    arguments:
      - '@service.user.finder-by-reference'
      - '@service.user-settings.finder-by-user'
      - '@service.user-data.finder-by-user'
      - '@factory.client'