services:
  DemigrantSoft\ClockInBot\Domain\Model\User\UserRepository:
    class: DemigrantSoft\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\User\UserDbalRepository
    parent: 'repository.dbal.base'

  DemigrantSoft\ClockInBot\Domain\Model\UserSettings\UserSettingsRepository:
    class: DemigrantSoft\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\UserSettings\UserSettingsDbalRepository
    parent: 'repository.dbal.base'

  DemigrantSoft\ClockInBot\Domain\Model\UserSchedule\UserScheduleRepository:
    class: DemigrantSoft\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\UserSchedule\UserScheduleDbalRepository
    parent: 'repository.dbal.base'

  DemigrantSoft\ClockInBot\Domain\Model\UserClientData\UserClientDataRepository:
    class: DemigrantSoft\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\UserSchedule\UserScheduleDbalRepository
    parent: 'repository.dbal.base'