services:
  # User
  service.user.creator:
    class: DemigrantSoft\ClockInBot\Domain\Service\User\UserCreator
    arguments:
      - '@repository.dbal.user'

  service.user.finder:
    class: DemigrantSoft\ClockInBot\Domain\Service\User\UserFinder
    arguments:
      - '@repository.dbal.user'

  service.user.finder-by-reference:
    class: DemigrantSoft\ClockInBot\Domain\Service\User\UserFinderByReference
    arguments:
      - '@repository.dbal.user'

  # Settings
  service.user-settings.creator:
    class: DemigrantSoft\ClockInBot\Domain\Service\UserSettings\UserSettingsCreator
    arguments:
      - '@repository.dbal.user-settings'

  service.user-settings.remover-by-user:
    class: DemigrantSoft\ClockInBot\Domain\Service\UserSettings\UserSettingsRemoverByUserId
    arguments:
      - '@repository.dbal.user-settings'

  service.user-settings.finder-by-user:
    class: DemigrantSoft\ClockInBot\Domain\Service\UserSettings\UserSettingsFinderByUserId
    arguments:
      - '@repository.dbal.user-settings'

  # Client Data
  service.user-data.creator:
    class: DemigrantSoft\ClockInBot\Domain\Service\UserClientData\UserClientDataCreator
    arguments:
      - '@repository.dbal.user-data'

  service.user-data.finder-by-user:
    class: DemigrantSoft\ClockInBot\Domain\Service\UserClientData\UserClientDataFinderByUserId
    arguments:
      - '@repository.dbal.user-data'

  # Schedule
  service.user-schedule.finder-by-user:
    class: DemigrantSoft\ClockInBot\Domain\Service\UserSchedule\UserScheduleFinderByUserId
    arguments:
      - '@repository.dbal.user-schedule'