parameters:
    db: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    sqlite_repository:
        class: App\Infrastructure\SqliteRepository
        arguments:
            - '%db%'

    repository.not-working-days:
        class: App\Infrastructure\NotWorkingDays\Repository\NotWorkingDaysSqliteRepository
        parent: sqlite_repository
        autowire: false
        autoconfigure: false

    http.client:
        class: App\Domain\Client\Client
        arguments:
            - "%env(BASE_URL)%"
            - "%env(USER)%"
            - "%env(PASS)%"

    command.checkin:
        class: App\Entrypoint\Command\CheckInCommand
        arguments:
            - '@http.client'
            - '@repository.not-working-days'
        tags:
            - { name: console.command, command: 'ocib:checkin' }
