parameters:
    db: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false

    sqlite_repository:
        class: App\Infrastructure\SqliteRepository
        arguments:
            - '%db%'

    repository.not-working-days:
        class: App\Infrastructure\NotWorkingDays\Repository\NotWorkingDaysSqliteRepository
        parent: sqlite_repository
        autowire: false
        autoconfigure: false

    http.client:
        class: App\Domain\Client\Client
        arguments:
            - "%env(OCEAN_URL)%"
            - "%env(USER)%"
            - "%env(PASS)%"
            - "%env(LAT)%"
            - "%env(LON)%"

    service.notification:
        class: App\Infrastructure\Notification\TelegramNotificationService
        arguments:
            - "%env(TELEGRAM_TOKEN)%"
            - "%env(TELEGRAM_CHAT_ID)%"

    command.checkin:
        class: App\Entrypoint\Command\CheckInCommand
        arguments:
            - '@http.client'
            - '@repository.not-working-days'
            - '@service.notification'
        tags:
            - { name: console.command, command: 'ocib:checkin:add' }

    command.get-checkins:
        class: App\Entrypoint\Command\GetCheckInsCommand
        arguments:
            - '@http.client'
            - '@service.notification'
        tags:
            - { name: console.command, command: 'ocib:checkin:get' }

    command.add-not-working-day:
        class: App\Entrypoint\Command\AddNotWorkingDaysCommand
        arguments:
            - '@repository.not-working-days'
        tags:
            - { name: console.command, command: 'ocib:not-working-days:add' }