parameters:
    db_url: '%env(resolve:DATABASE_URL)%'

services:


imports:
    - { resource: context/system/repository.yaml }
    - { resource: context/system/command.yaml }
    - { resource: context/user/repository.yaml }
    - { resource: context/user/service.yaml }
